name: achievement-rank

on: 
  schedule:
    - cron: '0/30 * * * *'

jobs:
  achievement-rank:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r Achievement/requirements.txt
    - name: Update Ranking Leaderboard
      run: |
        python3 Achievement/app.py
    - name: Commit Changes
      run: |
          git config --global user.name 'HanHan3z'
          git config --global user.email '1635233241@qq.com'
          git add -f AchievementRank.json
          git commit -m "Update Achievement Leaderboard"
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        force: true
